name: Build ISTA HO

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "The action was triggered

      - name: Wait for 20 seconds
        run: |
          echo "Sleeping for 20 seconds..."
          sleep 20
          echo "Done waiting."

